### ISSUE TITLE
Query async and streams

### ISSUE THREAD

**Issue by PhilAndrew** [manishkkatoch/scala-cypher-dsl#12]
Hi there! Quite interested in this - is there support for queries done asynchronously ?
Is there support for streams, I mean if the amount of data coming back is huge, then being able to process a stream would be more useful than reading all into RAM.

**Comment by manishkkatoch** [comment]
Hi Phil,

`scala-cypher-dsl` does not provide any networking interface to Neo4J instance. It merely provides a type-safe way to create the Neo4J queries. The ideal use case would be to express the Neo4J queries and use the query string and parameters map. These artefacts can be used to either connect via JDBC, or serialised and sent over API. There is no guidance over the connecting protocol.
