### ISSUE TITLE
Hi, an question.

### ISSUE THREAD

**Issue by zx0922** [manishkkatoch/scala-cypher-dsl#5]
First of all , thanks for your amazing blog. https://hackernoon.com/simulating-user-location-and-navigation-route-on-iphone-without-xcode-761f06905f1c

Have an short question.
 is it just change the location in this APP, not like using gpx file with Xcode , change the whole system location?

**Comment by manishkkatoch** [comment]
Hi @zx0922 

Sorry you tagged this to wrong repository and hence delayed response. The mocking is local to the application since the LocationManager mocking happens within the application code.
